// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vriscv_muldiv_csr_tb.h for the primary calling header

#include "Vriscv_muldiv_csr_tb__pch.h"
#include "Vriscv_muldiv_csr_tb_riscv_issue.h"

VL_ATTR_COLD void Vriscv_muldiv_csr_tb_riscv_issue___ctor_var_reset(Vriscv_muldiv_csr_tb_riscv_issue* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vriscv_muldiv_csr_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vriscv_muldiv_csr_tb_riscv_issue___ctor_var_reset\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->__PVT__clk_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rst_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_valid_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__fetch_pc_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__fetch_fault_fetch_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_fault_page_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_exec_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_lsu_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_branch_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_mul_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_div_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_csr_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_rd_valid_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_instr_invalid_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_exec_request_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_exec_is_taken_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_exec_is_not_taken_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_exec_source_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__branch_exec_is_call_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_exec_is_ret_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_exec_is_jmp_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_exec_pc_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__branch_d_exec_request_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_d_exec_pc_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__branch_d_exec_priv_i = VL_RAND_RESET_I(2);
    vlSelf->__PVT__branch_csr_request_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_csr_pc_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__branch_csr_priv_i = VL_RAND_RESET_I(2);
    vlSelf->__PVT__writeback_exec_value_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__writeback_mem_valid_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__writeback_mem_value_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__writeback_mem_exception_i = VL_RAND_RESET_I(6);
    vlSelf->__PVT__writeback_mul_value_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__writeback_div_valid_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__writeback_div_value_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_result_e1_value_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_result_e1_write_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__csr_result_e1_wdata_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_result_e1_exception_i = VL_RAND_RESET_I(6);
    vlSelf->__PVT__lsu_stall_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__take_interrupt_i = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fetch_accept_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_request_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__branch_pc_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__branch_priv_o = VL_RAND_RESET_I(2);
    vlSelf->__PVT__exec_opcode_valid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__lsu_opcode_valid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__csr_opcode_valid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mul_opcode_valid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__div_opcode_valid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__opcode_opcode_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__opcode_pc_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__opcode_invalid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__opcode_rd_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__opcode_ra_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__opcode_rb_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__opcode_ra_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__opcode_rb_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__lsu_opcode_opcode_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__lsu_opcode_pc_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__lsu_opcode_invalid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__lsu_opcode_rd_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__lsu_opcode_ra_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__lsu_opcode_rb_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__lsu_opcode_ra_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__lsu_opcode_rb_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__mul_opcode_opcode_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__mul_opcode_pc_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__mul_opcode_invalid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mul_opcode_rd_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__mul_opcode_ra_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__mul_opcode_rb_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__mul_opcode_ra_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__mul_opcode_rb_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_opcode_opcode_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_opcode_pc_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_opcode_invalid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__csr_opcode_rd_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__csr_opcode_ra_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__csr_opcode_rb_idx_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__csr_opcode_ra_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_opcode_rb_operand_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_writeback_write_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__csr_writeback_waddr_o = VL_RAND_RESET_I(12);
    vlSelf->__PVT__csr_writeback_wdata_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_writeback_exception_o = VL_RAND_RESET_I(6);
    vlSelf->__PVT__csr_writeback_exception_pc_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__csr_writeback_exception_addr_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__exec_hold_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mul_hold_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__interrupt_inhibit_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__retire_valid_o = VL_RAND_RESET_I(1);
    vlSelf->__PVT__retire_rd_o = VL_RAND_RESET_I(5);
    vlSelf->__PVT__retire_pc_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__retire_value_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x1_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x2_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x3_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x4_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x5_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x6_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x7_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x8_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x9_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x10_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x11_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x12_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x13_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x14_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x15_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x16_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x17_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x18_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x19_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x20_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x21_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x22_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x23_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x24_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x25_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x26_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x27_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x28_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x29_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x30_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__debug_x31_o = VL_RAND_RESET_I(32);
    vlSelf->__PVT__stall_w = VL_RAND_RESET_I(1);
    vlSelf->__PVT__priv_x_q = VL_RAND_RESET_I(2);
    vlSelf->__PVT__opcode_valid_w = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pipe_squash_e1_e2_w = VL_RAND_RESET_I(1);
    vlSelf->__PVT__opcode_issue_r = VL_RAND_RESET_I(1);
    vlSelf->__PVT__opcode_accept_r = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pipe_rd_e1_w = VL_RAND_RESET_I(5);
    vlSelf->__PVT__pipe_rd_e2_w = VL_RAND_RESET_I(5);
    vlSelf->__PVT__pipe_valid_wb_w = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pipe_rd_wb_w = VL_RAND_RESET_I(5);
    vlSelf->__PVT__issue_fault_w = VL_RAND_RESET_I(6);
    vlSelf->__PVT__div_pending_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__csr_pending_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__scoreboard_r = VL_RAND_RESET_I(32);
    vlSelf->__PVT__issue_b_ra_value_w = VL_RAND_RESET_I(32);
    vlSelf->__PVT__issue_b_rb_value_w = VL_RAND_RESET_I(32);
    vlSelf->__PVT__issue_ra_value_r = VL_RAND_RESET_I(32);
    vlSelf->__PVT__issue_rb_value_r = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__valid_e1_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__ctrl_e1_q = VL_RAND_RESET_I(10);
    vlSelf->__PVT__u_pipe_ctrl__DOT__pc_e1_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__npc_e1_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__opcode_e1_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__operand_ra_e1_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__operand_rb_e1_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__exception_e1_q = VL_RAND_RESET_I(6);
    vlSelf->__PVT__u_pipe_ctrl__DOT__valid_e2_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__ctrl_e2_q = VL_RAND_RESET_I(10);
    vlSelf->__PVT__u_pipe_ctrl__DOT__csr_wr_e2_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__csr_wdata_e2_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__result_e2_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__pc_e2_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__npc_e2_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__opcode_e2_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__operand_ra_e2_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__operand_rb_e2_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__exception_e2_q = VL_RAND_RESET_I(6);
    vlSelf->__PVT__u_pipe_ctrl__DOT__result_e2_r = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__valid_e2_w = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__load_store_e2_w = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__exception_e2_r = VL_RAND_RESET_I(6);
    vlSelf->__PVT__u_pipe_ctrl__DOT__squash_e1_e2_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__valid_wb_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__ctrl_wb_q = VL_RAND_RESET_I(10);
    vlSelf->__PVT__u_pipe_ctrl__DOT__csr_wr_wb_q = VL_RAND_RESET_I(1);
    vlSelf->__PVT__u_pipe_ctrl__DOT__csr_wdata_wb_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__result_wb_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__pc_wb_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__npc_wb_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__opcode_wb_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__operand_ra_wb_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__operand_rb_wb_q = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__exception_wb_q = VL_RAND_RESET_I(6);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_d__DOT__dbg_inst_str);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_d__DOT__dbg_inst_ra);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_d__DOT__dbg_inst_rb);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_d__DOT__dbg_inst_rd);
    vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_d__DOT__dbg_inst_imm = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_d__DOT__dbg_inst_pc = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_ctrl__DOT__u_trace_d__DOT____VdfgExtracted_h80d7e585__0);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_ctrl__DOT__u_trace_d__DOT____VdfgExtracted_hef8b1dcb__0);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_ctrl__DOT__u_trace_d__DOT____VdfgExtracted_h5dd7f615__0);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_wb__DOT__dbg_inst_str);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_wb__DOT__dbg_inst_ra);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_wb__DOT__dbg_inst_rb);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_wb__DOT__dbg_inst_rd);
    vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_wb__DOT__dbg_inst_imm = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_ctrl__DOT__u_trace_wb__DOT__dbg_inst_pc = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_h80d7e585__0);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_hef8b1dcb__0);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_ctrl__DOT__u_trace_wb__DOT____VdfgExtracted_h5dd7f615__0);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_dec0_verif__DOT__dbg_inst_str);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_dec0_verif__DOT__dbg_inst_ra);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_dec0_verif__DOT__dbg_inst_rb);
    VL_RAND_RESET_W(80, vlSelf->__PVT__u_pipe_dec0_verif__DOT__dbg_inst_rd);
    vlSelf->__PVT__u_pipe_dec0_verif__DOT__dbg_inst_imm = VL_RAND_RESET_I(32);
    vlSelf->__PVT__u_pipe_dec0_verif__DOT__dbg_inst_pc = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_dec0_verif__DOT____VdfgExtracted_h80d7e585__0);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_dec0_verif__DOT____VdfgExtracted_hef8b1dcb__0);
    VL_RAND_RESET_W(80, vlSelf->u_pipe_dec0_verif__DOT____VdfgExtracted_h5dd7f615__0);
}

VL_ATTR_COLD void Vriscv_muldiv_csr_tb_riscv_issue___configure_coverage(Vriscv_muldiv_csr_tb_riscv_issue* vlSelf, bool first) {
    (void)vlSelf;  // Prevent unused variable warning
    Vriscv_muldiv_csr_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+            Vriscv_muldiv_csr_tb_riscv_issue___configure_coverage\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    (void)first;  // Prevent unused variable warning
}
